sudo: required

language: bash

services:
 - docker

branches:
  only: 
    - master
    - latest
    - tools-1.8.8
    - tools-1.8.3
    - tools-1.8


install:
    - sudo mkdir /data
    - docker build -t bbriggs/spigot:1.8.3 .

script:
    - docker run -it -p 25565:25565 -v /data:/data -e EULA=true -e TRAVIS=true bbriggs/spigot:1.8.3

after_success:
    - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD --email=$DOCKER_EMAIL 
    - docker push bbriggs/spigot:1.8.3
